name: farsight
channels:
- defaults
dependencies:
- asn1crypto=0.23.0
- ca-certificates=2017.08.26
- certifi=2017.11.5
- cffi=1.11.2
- chardet=3.0.4
- cryptography=2.1.4
- cycler=0.10.0
- freetype=2.8
- idna=2.6
- intel-openmp=2018.0.0
- jpeg=9b
- libcxx=4.0.1
- libcxxabi=4.0.1
- libedit=3.1
- libffi=3.2.1
- libgfortran=3.0.1
- libpng=1.6.32
- libprotobuf=3.4.1
- libtiff=4.0.9
- matplotlib=2.1.1
- mkl=2018.0.1
- ncurses=6.0
- numpy=1.12.1
- olefile=0.44
- openssl=1.0.2n
- pillow=5.0.0
- pip=9.0.1
- protobuf=3.4.1
- pycparser=2.18
- pyopenssl=17.5.0
- pyparsing=2.2.0
- pyserial=3.4
- pysocks=1.6.7
- python=3.6.4
- python-dateutil=2.6.1
- pytz=2017.3
- readline=7.0
- requests=2.18.4
- setuptools=36.5.0
- six=1.11.0
- sqlite=3.20.1
- tk=8.6.7
- tornado=4.5.2
- urllib3=1.22
- werkzeug=0.12.2
- wheel=0.30.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - bleach==1.5.0
  - enum34==1.1.6
  - html5lib==0.9999999
  - markdown==2.6.11
  - opencv-python==3.4.0.12
  - setproctitle==1.1.10
  - tensorflow==1.4.1
  - tensorflow-tensorboard==0.4.0rc3
  - transitions==0.6.4
